[theme]
primaryColor = "#006437"
backgroundColor = "#f4fbf7"
secondaryBackgroundColor = "#e2f0e9"
textColor = "#222222"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false
